
proteina = "MGNQFWIYGLAGLLLSGSAAGVTAVYRNQSPPQMMAQQGMHMQWTDQSFIEMMTPHHQDAIDMAEMALQKAEHPELKKLARNIIRDQEREIKEMKRRYQQWFKRPVPALSSQGMMGMHQGHGMMAMDLDALATAQNFDREFIRQMIPHHQMAVMMASNLKTNTERPEMDKLMDDIIRSQSAEIKQMKQWYQNWYGQ"

dominio = proteina.find("RR") + 1


print(proteina.replace("RR","-rr-"))
print("el dominio RR esta en la posicion: "+ str(dominio))


